commonLabels:
  app.kubernetes.io/genereted-by: fineract

resources:
  # backend service
  - nylabank-fineract/fineract-mifoscommunity-deployment.yml
  - nylabank-fineract/fineract-server-deployment.yml

  # client
  - messagebroker-k8s/kafka.yml
  # monitoring prometheus

patchesJson6902:
